[project]
name = "neem-interface-python"
version = "1.0"
dependencies = [
    "roslibpy~=1.2.1",
    "tqdm",
    "scipy~=1.7.3"
]

[build-system]
requires      = ["setuptools>=61.0.0", "wheel"]
build-backend = "setuptools.build_meta"
